name: Update Firmware Metadata

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Firmware tag name'
        required: true

jobs:
  update-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout firmware_updates
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set tag name
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          fi

      - name: Debug tag name
        run: echo "TAG_NAME is $TAG_NAME"

      - name: Get release info
        id: release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          result-encoding: string
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: process.env.TAG_NAME
            });
            // Ensure release.data is a string
            const json = JSON.stringify(release.data);
            core.setOutput('result', json);
            return json;
        env:
          TAG_NAME: ${{ env.TAG_NAME }}

      - name: Print release step output
        run: echo "release.outputs.result=${{ steps.release.outputs.result }}"

      - name: Write release.json
        run: |
          if [ -z "${{ steps.release.outputs.result }}" ]; then
            echo '{}' > release.json
          else
            echo '${{ steps.release.outputs.result }}' > release.json
          fi

      - name: Debug release.json
        run: cat release.json

      - name: Generate firmware.json
        run: |
          if jq empty release.json; then
            jq -r --arg version "$TAG_NAME" '
              {
                version: $version,
                firmwares: (
                  [ .assets[] | { key: (.name | split("_")[0]), value: { filename: .name, url: .browser_download_url } } ]
                  | from_entries
                )
              }
            ' release.json > firmware.json
          else
            echo "release.json is not valid JSON. Exiting."
            cat release.json
            exit 1
          fi

      - name: Clone firmware-meta repo
        uses: actions/checkout@v4
        with:
          repository: rajputapoorva94/firmware-meta
          token: ${{ secrets.PAT_TOKEN }}
          path: meta

      - name: Copy and Commit firmware.json
        run: |
          cp firmware.json meta/
          cd meta
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add firmware.json
          git commit -m "Update firmware metadata for $TAG_NAME" || echo "No changes to commit"
          git push